#
# https://www.mydatahack.com/deploying-jekyll-site-to-github-page-with-github-actions/
# https://github.com/JamesIves/github-pages-deploy-action
#
name: Deploy to GitHub Page
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
    #- name: Build-Jekyll
    #  run: |
    #    sudo apt-get install ruby-full
    #    sudo gem install bundler
    #    sudo bundle install
    #    bundle exec jekyll build
    - name: Build-Jekyll-Fake
      run: |
         mkdir _site
         echo "Hello from GitHub Actions" > _site/index.txt
    - name: Deploy_To_GithubPage
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        ACCESS_TOKEN: ${{ secrets.GIT_PAGE_DEPLOY }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: _site # The folder the action should deploy.
        REPOSITORY_NAME: mincong-h/test
